version: '3'

services:
  app:
    container_name: node-app
    build:
      context: ./app
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    tty: true

  tracker:
    container_name: node-tracker
    build:
      context: ./tracker
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./tracker:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8081:8081
    tty: true

  client:
    container_name: node-client
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8082:8082
    tty: true